config/routes.rb
Rewsly::Application.routes.draw do
  devise_for :users
  resources :stories

   root 'stories#index'

  

end

app/models/storie.rb
class Storie < ActiveRecord::Base

	 validates :title, :link, :category, presence: true
 #    validates :description, length: { minimum: 10 }
 #    validates :year_released, numericality: {only_integer: true }
 #    validates :year_released, numericality: {greater_than: 0 }
 #    validates :rating, numericality: {greater_than: 0, less_than: 6 }
   # validates :rating, numericality: { smaller_than: 6 }

	def self.search_for(query)
		where('title LIKE :query OR category LIKE :query OR upvotes LIKE :query', query: "%#{query}%")
	end	

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  #before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Storie.search_for(params[:q])   
    #@stories = Storie.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    # @story = Storie.all
    @story = Storie.find(params[:id])
  end

  # GET /stories/new
  def new
    @story = Storie.new
  end

  # GET /stories/1/edit
  def edit
    @story = Storie.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Storie.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Storie was successfully created.' }
        format.json { render action: 'show', status: :created, location: @story }
      else
        format.html { render action: 'new' }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    
    @storie = Storie.find(params[:id])
    @storie.update story_params
    redirect_to @storie


    # respond_to do |format|
    #   if @story.update(story_params)
    #     format.html { redirect_to @story, notice: 'Storie was successfully updated.' }
    #     format.json { head :no_content }
    #   else
    #     format.html { render action: 'edit' }
    #     format.json { render json: @story.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @storie = Storie.find(params[:id])
    @storie.destroy
    redirect_to stories_path :notice => "Success!"  

    # @story.destroy
    # respond_to do |format|
    #   format.html { redirect_to stories_url }
    #   format.json { head :no_content }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Storie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
       params.require(:storie).permit(:title, :link, :upvotes, :category)
     # params.require(:story).permit(:title, :link, :upvotes, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rewsly</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= yield %>

</body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_area :link %>
  </div>
  <div class="field">
    <%= f.label :upvotes %><br>
    <%= f.number_field :upvotes %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/_list.html.erb
<table>
  <thead>
    <tr>
      <th>Title   </th>
      <th>Link    </th>
      <th>Upvotes  </th>
      <th>Category </th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<% @stories.each do |x| %>
 <tbody>

<tr>
	<td><b><%= link_to x.title, story_path(x.id) %> </b></td> 
	<td><%=x.link %> </td> 
	<td> | <i> <%=x.upvotes %> </i> | </td> 
	<td> - <%= x.category %> </td> 
	<td><%= link_to 'Show', story_path(x.id) %></td>
	<td><%= link_to "Edit", edit_story_path(x.id) %> </td> 
	<td><%= link_to "Delete", x, method: :delete, data: { confirm: 'Are you sure?' } %></td> </br>

</tr>
<% end %>
</tbody>
</table>
<br/>

<h3>Stories with rating larger than 1</h3>
<table>
  <thead>
    <tr>
      <th>Title   </th>
      <th>Link    </th>
      <th>Upvotes  </th>
      <th>Category </th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<% @stories.each do |x| %>

<!--Question: Is this the best way to implement this? Are there alternatives? -->
<% if x.upvotes > 1 %>
<tbody>

<tr>
	<td><b><%= link_to x.title, story_path(x.id) %> </b></td> 
	<td><%=x.link %> </td> 
	<td> | <i> <%=x.upvotes %> </i> | </td> 
	<td> - <%= x.category %> </td> 
	<td><%= link_to 'Show', story_path(x.id) %></td>
	<td><%= link_to "Edit", edit_story_path(x.id) %> </td> 
	<td><%= link_to "Delete", x, method: :delete, data: { confirm: 'Are you sure?' } %></td> </br>


</tr>
<% end %>
<% end %>
</tbody>
</table>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>Welcome to Rewsly</h1>

<h5><%= link_to "Add new story", new_story_path %></h5>

<%= form_tag "/", method: "Get" do %>
  <%= text_field_tag :q %>
  <%= submit_tag "Search" %>
<% end %>


<%= render "list" %> 

<!-- </br>
</br>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th>Upvotes</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= link_to story.title, story %></td>
        <td><%= story.link %></td>
        <td><%= story.upvotes %></td>
        <td><%= story.category %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br> -->
<br/>
<%= link_to 'Refresh', root_path %>
<%= link_to 'New Storie', new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Story</h1>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Link:</strong>
  <%= @story.link %>
</p>

<p>
  <strong>Upvotes:</strong>
  <%= @story.upvotes %>
</p>

<p>
  <strong>Category:</strong>
  <%= @story.category %>
</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>